version: "3.9"
services:
    db:
        image: postgres:13-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fastapi-db
        volumes:
            - fastapi-data:/var/lib/postgres/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    api:
        build: .
        command: sh -c "uvicorn app:app --host 0.0.0.0 --port 80 --reload"
        volumes:
            - .:/src
        ports:
            - "8000:80"
        depends_on:
            - db
volumes:
    fastapi-data:
        driver: local
    