version: "3.9"
services:
    api_db:
        image: postgres:13-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fastapidb
        volumes:
            - fastapi-data:/var/lib/postgres/data
            - ./api/api_v1/storage/init.sql:/docker-entrypoint-initdb.d/init.sql
    api:
        image: meschac38000/fast-api:latest
        volumes:
            - .:/src/app
        ports:
            - 8000:80
        links:
            - api_db
        environment:
            DATABASE_HOST: db
volumes:
    fastapi-data:
        driver: local