name: Build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    name: Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/common.txt -r requirements/dev.txt

      - name: Running Flake8
        run: flake8

      - name: Running unit-tests and code-coverage
        run: pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          flags: code coverage
          name: Test-FastAPI
          fail_ci_if_error: true
          verbose: true
