name: Deploy

on:
  workflow_run:
    workflows:
      - "Black"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy docker image
    steps:
      - uses: actions/checkout@master

      - name: Build & push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: meschac38000/fast-api
          tags: latest
          dockerfile: Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
