name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install black dependencie
        run: |
          python -m pip install --upgrade pip
          pip install black==21.5b0
      - uses: psf/black@stable
        with:
          args: ". --check"
      - name: Reformatting code
        if: failure()
        run: |
          black .
          git config --global user.name 'Eliam LOTONGA'
          git config --global user.email 'e.m.lotonga@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "Fixup: format code with Black"
          git push
