# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Workflow

on:
  workflow_run:
    workflows:
      - "Auto-format"
    types:
      - completed
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@master
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/common.txt -r requirements/dev.txt

      - name: Running Flake8
        run: flake8

      - name: Running unit-tests and code-coverage
        run: pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          working-directory: .
          files: ./coverage.xml
          flags: code coverage
          name: Test-FastAPI
          fail_ci_if_error: true
          verbose: true
